### ISSUE TITLE
Add default background on iOS.

### ISSUE THREAD

**Issue by brunoziie** [henrychavez/nativescript-bottom-navigation#33] opened 2018-09-27 15:16 UTC
When backgroundColor is omited on iOS the app crashes.

```
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error: Expected 1 or 4 constructor parameters.
at
1   Color@file:///app/tns_modules/tns-core-modules/color/color-common.js:31:75
2   Color@file:///app/tns_modules/tns-core-modules/color/color.js:6:47
3   initNativeView@file:///app/tns_modules/nativescript-bottom-navigation/bottom-navigation.js:61:57
```

**Comment by henrychavez** [comment] 2018-09-27 15:28
The problem is the `keyLineColor` that property is deprecated because now I'm using BottomNavigation from `material-components-ios` trying removing that

**Comment by brunoziie** [comment] 2018-09-27 15:32
@henrychavez I got this error when try do this:

```xml
<bottomNav:BottomNavigation
    id="nav"
    activeColor="#FF8000"
    inactiveColor="#BECBD2"
    keyLineColor="#000000"
    loaded="bottomNavigationLoaded"
>
    <bottomNav:BottomNavigationTab icon="home"></bottomNav:BottomNavigationTab>
    <bottomNav:BottomNavigationTab icon="calendar"></bottomNav:BottomNavigationTab>
    <bottomNav:BottomNavigationTab icon="notifications"></bottomNav:BottomNavigationTab>
</bottomNav:BottomNavigation>
```

When I set `backgroundColor="#FFFFFF"` works fine.

In error stack the following line:

```initNativeView@file:///app/tns_modules/nativescript-bottom-navigation/bottom-navigation.js:61:57```

is where is defined the background color.
When the color is omited the Color constructor of NativeScript fail, then the app crashes.

**Comment by henrychavez** [comment] 2018-09-27 15:37
as you can see in the demo app I'm not setting the `backgroundColor` and there is no error,

can you please remove the `keyLineColor`?

**Comment by brunoziie** [comment] 2018-09-27 15:41
I removed the `keyLineColor` and the error keeps happening.

**Comment by henrychavez** [comment] 2018-09-27 15:43
can u please try `tns plugin remove nativescript-bottom-navigation`
then `tns plugin add nativescript-bottom-navigation`

**Comment by brunoziie** [comment] 2018-10-01 17:35
I did. Nothing changes.

**Comment by henrychavez** [comment] 2018-10-08 01:17
I couldn't reproduce the error, please update the plugin to 1.4.1 just in case.

I'm closing this issue because isn't reproducible.

**Closed by henrychavez** 2018-10-08 01:17 UTC
Labels: ios
