### ISSUE TITLE
Support Swift 4.0 ? 

### ISSUE THREAD

**Issue by alexandruantonica** [henrychavez/nativescript-bottom-navigation#31] opened 2018-08-26 16:12 UTC
Hi @henrychavez 
I've noticed that the plugin shows some errors when the XCode try to compile it with Swift 4.0. 

Do you have some free time to make it work with Swift 4.0, please?

**Comment by alexandruantonica** [comment] 2018-08-31 11:31
@henrychavez Hi 
Any news ?

**Comment by alexandruantonica** [comment] 2018-09-01 22:39
I see. 
Can you publish a version only with this Swift 4.0 support and then you can upgrade it with material components, please? 

Thanks ;)

**Comment by henrychavez** [comment] 2018-09-03 20:28
Yes, I can do that for now. The update will be ready for tomorrow

**Comment by alexandruantonica** [comment] 2018-09-05 20:02
@henrychavez Do you have any good news for me? 
Thanks.

**Comment by henrychavez** [comment] 2018-09-07 00:39
@alexandruantonica yes my friend!

can u please delete ur platform ios folder and recompile or just remove and add the plugin again should be fixed.

Happy coding!

**Comment by henrychavez** [comment] 2018-09-14 16:44
@alexandruantonica it works?

**Comment by alexandruantonica** [comment] 2018-09-19 08:16
Hi @henrychavez 
I had a problem I couldn't find a reason or a better explanation. 
I removed the folders (`platform` and `node_modules`), the Podfile is updated, everything is fine.
When I open my application and go to the page that use BottomBar the app freeze without any error. I had to open the app in debug mode and I've noticed this error message : 
```
2018-09-19 09:06:42.202847+0100  localhost ...[81207]: (libswiftCore.dylib) /Users/.../myapp/platforms/ios/Pods/MiniTabBar/MiniTabBar/Classes/MiniTabBar.swift: 32: 20: Fatal error: Use of unimplemented initializer 'init(frame:)' for class 'MiniTabBar.MiniTabBar'
```

Let me know if this make sense for you.

**Comment by henrychavez** [comment] 2018-09-20 21:32
weird.... let me try to replicate the error.

Are you using the nativescript cli? or compiling using xcode?

**Comment by alexandruantonica** [comment] 2018-09-21 06:26
I've tried to replicate it a few times and every time I have the same problem. 
Let me know if you need more info from me. 
I'm using nativescript cli.

**Comment by henrychavez** [comment] 2018-09-21 15:32
@alexandruantonica I already compiled and it works without problems.

Can you detail me the steps that you did? Probably is something when you build the app with xcode

**Comment by alexandruantonica** [comment] 2018-09-21 16:47
@henrychavez I guess I found the problem. 
In my packages.json I have these : 
```
...
"nativescript-bottom-navigation": "^1.2.0",
...
 "nativescript-cfalert-dialog": "^1.0.10",
```
If I keep the `cfalert-dialog` I got the error above regarding `MiniTabBar` (weird).
If I remove the `cfalert-dialog` (from package.json and the implementation from the app) everything works perfectly except the fact I don't have the `cfalert-dialog` anymore and I need it :) 

I've checked the `cfalert-dialog` plugin but I don't see any problems with it. 
Can you see anything wrong? Why these 2 plugins are not compatible? 

Thanks ;)

**Comment by henrychavez** [comment] 2018-09-21 22:21
Yes, the problem is that `nativescript-cfalert-dialog` is targeting the version 4 of swift

Let me try some workaround so you can have both plugins working together :D

**Comment by alexandruantonica** [comment] 2018-09-24 10:44
@henrychavez Hi
Do you have any news for me? 
Thanks.

**Comment by henrychavez** [comment] 2018-09-24 14:49
@alexandruantonica hi!
No I'm still doing some research about the issue and I didn't have the time in the weekend to look at it.
I'll try to find a solution these days

**Comment by alexandruantonica** [comment] 2018-09-24 17:06
@henrychavez I've tried few things to change in the Podfile of `nativescript-cfalert-dialog` : 
- change the target from `4.0` to `3.0` 
- remove the target at all 
It didn't work.

**Comment by henrychavez** [comment] 2018-09-24 17:34
It doesn't work if you only remove it from the Podfile you have to remove it form the `build.xcconfig` too and if you put the swift version on ur project Podfile or `build.xcconfig` 

That should do the work for now :D

**Closed** 2018-09-26 22:30 UTC
Labels: enhancement

**Comment by championswimmer** [comment] 2018-10-04 13:18
This plugin is incompatible with all Swift 3 plugins. This is absurd to force Swift 4 to everyone when 100% of rest of the world isn't using it yet
