### ISSUE TITLE
Angular build error[BUG] 

### ISSUE THREAD

**Issue by ElesGergo** [henrychavez/nativescript-bottom-navigation#77] opened 2019-09-16 14:27 UTC
**Before start:**
 - Make sure to check the demo app(s) for sample usage
 - Make sure to check the existing issues in this repository 
 - If the demo apps cannot help and there is no issue for your problem, tell us about it

---

**Which platform(s) does your issue occur on?**
- [ x] iOS
- [ ] Android

**What type of device?**
- [ ] Emulator
- [ x] Device

**Please, provide the following version numbers that your issue occurs with:**

- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

**Please, tell us how to recreate the issue in as much detail as possible.**
Describe the steps to reproduce the behavior:
2. Click on '...'
3. See error

**Is there any code involved?**
- Provide a code example to recreate the problem 
- (EVEN BETTER) Provide a .zip with an application or refer to a repository with an application where the problem is reproducible.

ERROR in node_modules/nativescript-bottom-navigation/index.d.ts(21,3): error TS2416: Property 'activeColor' in type 'BottomNavigationBar' is not assignable to the same property in base type 'BottomNavigationBarBase'.
[19-09-16 16:19:46.568] (CLI)   Type 'string' is not assignable to type 'Color'.
[19-09-16 16:19:46.568] (CLI) node_modules/nativescript-bottom-navigation/index.d.ts(22,3): error TS2416: Property 'inactiveColor' in type 'BottomNavigationBar' is not assignable to the same property in base type 'BottomNavigationBarBase'.
[19-09-16 16:19:46.568] (CLI)   Type 'string' is not assignable to type 'Color'.
[19-09-16 16:19:46.568] (CLI) node_modules/nativescript-bottom-navigation/index.d.ts(23,20): error TS2304: Cannot find name 'Color'.
[19-09-16 16:19:46.568] (CLI) node_modules/nativescript-bottom-navigation/index.d.ts(46,22): error TS2304: Cannot find name 'EventData'.

Build error. Importing the missing  things and changing the string to color solves the problem however it is not possible with cloud build.

**Comment by henrychavez** [comment] 2019-09-16 15:06
The issue is fixed in release 2.0.4 please update the plugin in your package.json

**Closed by henrychavez** 2019-09-16 15:06 UTC
Labels: bug, help wanted
